-- Localizzazione italiana completa dei comandi. Alias, placeholder e sintassi sono preservati.
INSERT INTO `emulator_texts` (`key`, `value`) VALUES
    ('commands.cmd_promote_offer.info', 'informazioni'),
    ('commands.cmd_promote_offer.list', 'Tutte le offerte disponibili (%amount%):<br>%list%'),
    ('commands.cmd_promote_offer.list.entry', '%id%: %title% %description%'),
    ('commands.description.acc_debug', ':test [intestazione] i:1 s:a b:1'),
    ('commands.description.acc_modtool_room_info', 'Consente di visualizzare le informazioni sulla stanza nello strumento di moderazione.'),
    ('commands.description.cmd_about', ':about'),
    ('commands.description.cmd_add_youtube_playlist', ':add_youtube <base_item_id> <youtube_playlist_id>'),
    ('commands.description.cmd_alert', ':alert <username> <message>'),
    ('commands.description.cmd_allow_trading', 'Abilita/disabilita il tradelock per un utente.'),
    ('commands.description.cmd_badge', ':badge <username> <badge>'),
    ('commands.description.cmd_ban', ':ban <username> <time in seconds>'),
    ('commands.description.cmd_blockalert', ':blockalert'),
    ('commands.description.cmd_bots', ':bots'),
    ('commands.description.cmd_brb', ':brb'),
    ('commands.description.cmd_buildheight', ':buildheight [altezza]'),
    ('commands.description.cmd_bundle', ':bundle'),
    ('commands.description.cmd_buyroom', ':buyroom'),
    ('commands.description.cmd_calendar', ':calendar'),
    ('commands.description.cmd_changename', ':changename'),
    ('commands.description.cmd_chatcolor', ':chat [colorido = 0]'),
    ('commands.description.cmd_closedice', ':closedice [tutti]'),
    ('commands.description.cmd_commands', ':commands'),
    ('commands.description.cmd_connect_camera', ':connectcamera'),
    ('commands.description.cmd_control', ':control <username>'),
    ('commands.description.cmd_coords', ':coords'),
    ('commands.description.cmd_credits', ':credits <username> <amount>'),
    ('commands.description.cmd_dance', 'ballare in giro per il mondo! utilizzare 1 t/m 4 e 0 per fermarsi'),
    ('commands.description.cmd_danceall', ':danceall <dance id>'),
    ('commands.description.cmd_diagonal', ':diagonal'),
    ('commands.description.cmd_disablemassmentions', ':disablemassmentions'),
    ('commands.description.cmd_disablementions', ':disablementions'),
    ('commands.description.cmd_disable_effects', ':disableffects'),
    ('commands.description.cmd_disconnect', ':disconnect <username>'),
    ('commands.description.cmd_duckets', ':duckets <username> <amount>'),
    ('commands.description.cmd_ejectall', ':ejectall'),
    ('commands.description.cmd_empty', ':empty <username>'),
    ('commands.description.cmd_empty_bots', ':emptybots'),
    ('commands.description.cmd_empty_pets', ':emptypets'),
    ('commands.description.cmd_enable', ':enable <id>, :effect <id>, :eff <id> oppure :effect elenco'),
    ('commands.description.cmd_event', ':event <message>'),
    ('commands.description.cmd_explain', ':explain <command>'),
    ('commands.description.cmd_faceless', ':faceless'),
    ('commands.description.cmd_fastwalk', ':fastwalk'),
    ('commands.description.cmd_filterword', ':filter <word> [sostituzione]'),
    ('commands.description.cmd_freeze', ':freeze <username>'),
    ('commands.description.cmd_freeze_bots', ':freezebots'),
    ('commands.description.cmd_furnidata', ':furnidata'),
    ('commands.description.cmd_gift', ':gift <username> <itemid>'),
    ('commands.description.cmd_give_prefix', ':giveprefix <username> <text> <color> [icona] [effetto]'),
    ('commands.description.cmd_give_rank', ':giverank <username> <rank>'),
    ('commands.description.cmd_give_respect_points', ':give_respect_points <utente> <quantità> - Aggiunge punti rispetto da spendere.'),
    ('commands.description.cmd_ha', ':ha <message>'),
    ('commands.description.cmd_hal', ':hal <url> <message>'),
    ('commands.description.cmd_hand_item', ':handitem <id> oppure :handitem elenco'),
    ('commands.description.cmd_happyhour', ':happyhour'),
    ('commands.description.cmd_hidewired', ':hidewired'),
    ('commands.description.cmd_hoverboard', ':hoverboard'),
    ('commands.description.cmd_hug', ':hug <username>'),
    ('commands.description.cmd_invisible', ':invisible'),
    ('commands.description.cmd_ip_ban', ':ipban <username> [motivo]'),
    ('commands.description.cmd_kickall', ':kickall <message>'),
    ('commands.description.cmd_kill', ':kill <username>'),
    ('commands.description.cmd_kiss', ':kiss <username>'),
    ('commands.description.cmd_lay', ':lay'),
    ('commands.description.cmd_list_prefixes', ':listprefixes <username>'),
    ('commands.description.cmd_machine_ban', ':machineban <username> [motivo]'),
    ('commands.description.cmd_massbadge', ':massbadge <badge>'),
    ('commands.description.cmd_masscredits', ':masscredits <amount>'),
    ('commands.description.cmd_massduckets', ':massduckets <amount>'),
    ('commands.description.cmd_massgift', ':massgift <itemid>'),
    ('commands.description.cmd_masspoints', ':masspoints <amount> [tipo]'),
    ('commands.description.cmd_mimic', ':mimic <username>'),
    ('commands.description.cmd_moonwalk', ':moonwalk'),
    ('commands.description.cmd_multi', ':multi'),
    ('commands.description.cmd_mute', ':mute <username>'),
    ('commands.description.cmd_nuke', ':nuke <username>'),
    ('commands.description.cmd_pay', ':pay <username> <amount> <currency>'),
    ('commands.description.cmd_pet_info', ':petinfo <petname>'),
    ('commands.description.cmd_pickall', ':pickall'),
    ('commands.description.cmd_plugins', ':plugins'),
    ('commands.description.cmd_points', ':points <username> <amount> [tipo]'),
    ('commands.description.cmd_promote_offer', ':promoteoffer <offer_id> [informazioni]'),
    ('commands.description.cmd_pull', ':pull <username>'),
    ('commands.description.cmd_push', ':push <username>'),
    ('commands.description.cmd_randomword', ':rw <word>'),
    ('commands.description.cmd_redeem', ':redeem'),
    ('commands.description.cmd_reload_room', ':reload_room'),
    ('commands.description.cmd_remove_prefix', ':removeprefix <username> <id|all>'),
    ('commands.description.cmd_roomalert', ':roomalert <message>'),
    ('commands.description.cmd_roombadge', ':roombadge <badge>'),
    ('commands.description.cmd_roomcredits', ':roomcredits <amount>'),
    ('commands.description.cmd_roomeffect', ':roomeffect [id effetto]'),
    ('commands.description.cmd_roomgift', ':roomgift <item_id> [messaggio]'),
    ('commands.description.cmd_roomitem', ':roomitem [elementomid]'),
    ('commands.description.cmd_roommute', ':roommute'),
    ('commands.description.cmd_roompixels', ':roompixels <amount>'),
    ('commands.description.cmd_roompoints', ':roompoints <amount>'),
    ('commands.description.cmd_say', ':say <username> <text>'),
    ('commands.description.cmd_say_all', ':sayall <message>'),
    ('commands.description.cmd_sellroom', ':sellroom <diamonds>'),
    ('commands.description.cmd_set', 'Informazioni su :set'),
    ('commands.description.cmd_setmax', ':setmax <amount>'),
    ('commands.description.cmd_setpublic', ':setpublic'),
    ('commands.description.cmd_setroom_template', ':setroom_template'),
    ('commands.description.cmd_setrotation', ':rot;rotazione'),
    ('commands.description.cmd_setspeed', ':setspeed <speed>'),
    ('commands.description.cmd_setstate', ':ss'),
    ('commands.description.cmd_set_poll', ':setpoll <id>'),
    ('commands.description.cmd_shout', ':makeshout <username> <text>'),
    ('commands.description.cmd_shout_all', ':shoutall <message>'),
    ('commands.description.cmd_shutdown', ':shutdown'),
    ('commands.description.cmd_sit', ':sit'),
    ('commands.description.cmd_sitdown', ':sitdown'),
    ('commands.description.cmd_slime', ':slime <username>'),
    ('commands.description.cmd_snowwar_save', ':snowwarsave - pubblica il layout della stanza dell''editor di SnowWar'),
    ('commands.description.cmd_staffalert', ':sA <message>'),
    ('commands.description.cmd_staffonline', ':staffonline [classifica minima]'),
    ('commands.description.cmd_stalk', ':stalk <username>'),
    ('commands.description.cmd_summon', ':summon <username>'),
    ('commands.description.cmd_summonrank', ':summonrank <rankid>'),
    ('commands.description.cmd_superpull', ':spull <username>'),
    ('commands.description.cmd_super_ban', ':superban <username> [motivo]'),
    ('commands.description.cmd_take_badge', ':takebadge <username> <badge>'),
    ('commands.description.cmd_talk', ':talk <username> <message>'),
    ('commands.description.cmd_teleport', ':teleport'),
    ('commands.description.cmd_transform', ':transform <name> <race> <color>'),
    ('commands.description.cmd_trash', ':trash'),
    ('commands.description.cmd_unban', ':unban <username>'),
    ('commands.description.cmd_unload', ':unload'),
    ('commands.description.cmd_unmute', ':unmute <username>'),
    ('commands.description.cmd_update_achievements', ':update_achievements'),
    ('commands.description.cmd_update_all', ':update_all'),
    ('commands.description.cmd_update_bots', ':update_bots'),
    ('commands.description.cmd_update_calendar', ':update_calendar'),
    ('commands.description.cmd_update_catalogue', ':update_catalog'),
    ('commands.description.cmd_update_chat_bubbles', ':update_chat_bubbles'),
    ('commands.description.cmd_update_config', ':update_config'),
    ('commands.description.cmd_update_guildparts', ':update_guild_parts'),
    ('commands.description.cmd_update_hotel_view', ':update_hotel_view'),
    ('commands.description.cmd_update_items', ':update_items'),
    ('commands.description.cmd_update_navigator', ':update_navigator'),
    ('commands.description.cmd_update_permissions', ':update_permissions'),
    ('commands.description.cmd_update_pet_data', ':update_petdata'),
    ('commands.description.cmd_update_plugins', ':update_plugins'),
    ('commands.description.cmd_update_polls', ':update_polls'),
    ('commands.description.cmd_update_texts', ':update_texts'),
    ('commands.description.cmd_update_wordfilter', ':update_word_filter'),
    ('commands.description.cmd_update_words', ':update_words'),
    ('commands.description.cmd_update_youtube_playlists', ':update_youtube'),
    ('commands.description.cmd_userinfo', ':userinfo <username>'),
    ('commands.description.cmd_welcome', ':welcome <username>'),
    ('commands.description.cmd_word_quiz', ':wordquiz <question>'),
    ('commands.error.cmd_add_youtube_playlist.failed_playlist', 'Errore: impossibile recuperare la playlist YouTube specificata.'),
    ('commands.error.cmd_add_youtube_playlist.no_base_item', 'Impossibile trovare un articolo di base con quell''ID.'),
    ('commands.error.cmd_add_youtube_playlist.usage', 'Utilizzo: base_item_id youtube_playlist_id'),
    ('commands.error.cmd_alert.forgot_message', 'Si prega di fornire un messaggio!'),
    ('commands.error.cmd_alert.forgot_username', 'Si prega di fornire un nome utente!'),
    ('commands.error.cmd_alert.user_offline', 'Four Oh Four - \\r %user% non sembra essere online!'),
    ('commands.error.cmd_allow_trading.forgot_trade', 'Specifica se desideri abilitare il trading per %username%.'),
    ('commands.error.cmd_allow_trading.forgot_username', 'Specifica l''utente per cui abilitare/disabilitare il trading.'),
    ('commands.error.cmd_allow_trading.incorrect_setting', 'Utilizza %enabled% per abilitare il trading. Utilizza %disabled% per disattivare il trading.'),
    ('commands.error.cmd_allow_trading.user_not_found', 'L''Habbo target non esiste.'),
    ('commands.error.cmd_badge.already_owned', '%user% possiede già %badge%'),
    ('commands.error.cmd_badge.already_owns', 'L''utente %user% possiede già %badge%.'),
    ('commands.error.cmd_badge.forgot_badge', 'Specifica un badge da dare a %user%.'),
    ('commands.error.cmd_badge.forgot_username', 'Specifica un utente a cui assegnare il badge.'),
    ('commands.error.cmd_ban.ban_self', 'Non puoi vietarti.'),
    ('commands.error.cmd_ban.forgot_time', 'Si prega di fornire un tempo in secondi!'),
    ('commands.error.cmd_ban.forgot_user', 'Si prega di fornire un nome utente!'),
    ('commands.error.cmd_ban.invalid_time', 'Si prega di utilizzare un numero valido.'),
    ('commands.error.cmd_ban.target_rank_higher', 'L''Habbo che vuoi bannare ha un rango più alto del tuo.'),
    ('commands.error.cmd_ban.time_to_short', 'Il tempo di ban deve essere superiore a 600 secondi (che equivalgono a 10 minuti).'),
    ('commands.error.cmd_ban.user_offline', 'Impossibile trovare la destinazione.'),
    ('commands.error.cmd_bundle.duplicate', 'Ops! Sembra che questa stanza sia già in vendita.'),
    ('commands.error.cmd_bundle.missing_params', 'L''utilizzo corretto è :bundle <parent_id> <credits> <points> <points_type>'),
    ('commands.error.cmd_chatcolor.banned', 'Siamo spiacenti, quel chatcolor non è consentito.'),
    ('commands.error.cmd_chatcolor.no_number', 'Fornisci un ID colore.'),
    ('commands.error.cmd_chatcolor.numbers', 'Solo numeri positivi per favore!'),
    ('commands.error.cmd_control.not_found', 'Impossibile trovare l''utente %user%!'),
    ('commands.error.cmd_control.not_self', 'Non puoi controllarti *facepalm*'),
    ('commands.error.cmd_credits.invalid_amount', 'Si prega di utilizzare un numero valido.'),
    ('commands.error.cmd_credits.user_not_found', 'Potrebbe inviare %amount% crediti a %user%. %user% non esiste.'),
    ('commands.error.cmd_credits.user_offline', 'Impossibile trovare l''utente %user%.'),
    ('commands.error.cmd_danceall.invalid_dance', 'Si prega di utilizzare un numero valido!'),
    ('commands.error.cmd_danceall.no_dance', 'Si prega di specificare un ballo da 0 a 4!'),
    ('commands.error.cmd_danceall.outside_bounds', 'Utilizza un numero compreso tra 0 e 4'),
    ('commands.error.cmd_disconnect.disconnect_self', 'Non puoi disconnetterti!'),
    ('commands.error.cmd_disconnect.forgot_username', 'Si prega di fornire un nome utente!'),
    ('commands.error.cmd_disconnect.higher_rank', 'L''Habbo che volevi disconnettere è più importante di te.'),
    ('commands.error.cmd_disconnect.user_offline', 'Utente non trovato.'),
    ('commands.error.cmd_duckets.invalid_amount', 'Si prega di utilizzare un numero valido.'),
    ('commands.error.cmd_duckets.user_offline', 'Impossibile trovare l''utente %user%.'),
    ('commands.error.cmd_enable.not_allowed', 'Non hai il permesso per impostare questo effetto!'),
    ('commands.error.cmd_filterword.error', 'Impossibile aggiungere la parola al filtro parole. Possibile duplicato?'),
    ('commands.error.cmd_filterword.missing_word', 'Specificare la parola da filtrare, con una sostituzione facoltativa.'),
    ('commands.error.cmd_freeze.not_found', 'Impossibile trovare l''utente %user%.'),
    ('commands.error.cmd_gift.not_a_number', 'Solo numeri positivi'),
    ('commands.error.cmd_gift.not_found', '%itemid% non trovato!'),
    ('commands.error.cmd_gift.user_not_found', '%username% non trovato online.'),
    ('commands.error.cmd_give_prefix.invalid_color', 'Formato colore non valido. Utilizza il formato esadecimale (#FF0000).'),
    ('commands.error.cmd_give_prefix.too_long', 'Il testo del prefisso è troppo lungo (massimo 15 caratteri).'),
    ('commands.error.cmd_give_prefix.usage', 'Utilizzo: :giveprefix <username> <text> <color> [icona] [effetto]'),
    ('commands.error.cmd_give_prefix.user_not_found', 'Utente non trovato o non online.'),
    ('commands.error.cmd_give_rank.higher', 'Non puoi classificare %username% a un livello più alto del tuo!'),
    ('commands.error.cmd_give_rank.higher.other', '%username% ha un rango più alto del tuo e quindi non può cambiarlo!'),
    ('commands.error.cmd_give_rank.missing_rank', 'Grado mancante. Utilizzo:'),
    ('commands.error.cmd_give_rank.missing_username', 'Nome utente mancante. Utilizzo:'),
    ('commands.error.cmd_give_rank.not_found', 'La posizione %id% non è stata trovata!'),
    ('commands.error.cmd_give_rank.user_offline', '%username% non è online!'),
    ('commands.error.cmd_give_respect_points.invalid_amount', 'Inserisci una quantità positiva non superiore a %max%.'),
    ('commands.error.cmd_give_respect_points.storage', 'Impossibile salvare i punti rispetto. Riprova.'),
    ('commands.error.cmd_give_respect_points.usage', 'Utilizzo: :give_respect_points <utente> <quantità>'),
    ('commands.error.cmd_give_respect_points.user_not_found', 'Utente %user% non trovato.'),
    ('commands.error.cmd_ha.forgot_message', 'Si prega di fornire un messaggio!'),
    ('commands.error.cmd_ip_ban.ban_self', 'Non puoi bannare l''IP da solo!'),
    ('commands.error.cmd_kick.unkickable', '%username% non è calciabile!'),
    ('commands.error.cmd_list_prefixes.usage', 'Utilizzo: :listprefixes <username>'),
    ('commands.error.cmd_list_prefixes.user_not_found', 'Utente non trovato o non online.'),
    ('commands.error.cmd_machine_ban.ban_self', 'Non puoi emettere un MAC Ban!'),
    ('commands.error.cmd_massbadge.no_badge', 'Nessun distintivo specificato!'),
    ('commands.error.cmd_masscredits.invalid_amount', 'Si prega di utilizzare un numero valido.'),
    ('commands.error.cmd_massduckets.invalid_amount', 'Si prega di utilizzare un numero valido.'),
    ('commands.error.cmd_masspoints.invalid_amount', 'Si prega di utilizzare un numero valido.'),
    ('commands.error.cmd_masspoints.invalid_type', 'Tipo di punti non valido. Scegli tra: %types%'),
    ('commands.error.cmd_mimic.blocked', 'Non puoi copiare %user% %gender_name% guarda!'),
    ('commands.error.cmd_mimic.forbidden_clothing', 'L''altro utente ha dei vestiti che non possiedi ancora.'),
    ('commands.error.cmd_mimic.not_found', 'Impossibile trovare l''utente %user%!'),
    ('commands.error.cmd_mimic.not_self', 'Non puoi copiare te stesso!'),
    ('commands.error.cmd_mute.not_found', 'Impossibile trovare l''utilizzo %user%.'),
    ('commands.error.cmd_mute.not_specified', 'Specifica un utente da disattivare.'),
    ('commands.error.cmd_mute.self', 'Non puoi disattivare l''audio.'),
    ('commands.error.cmd_mute.time', 'Il tempo di silenzio deve essere di almeno 1 secondo.'),
    ('commands.error.cmd_pet_info.pet_not_found', '"Per favore, fornisci un nome da compagnia!"'),
    ('commands.error.cmd_points.invalid_amount', 'Si prega di utilizzare un numero valido.'),
    ('commands.error.cmd_points.invalid_type', 'Tipo di punti non valido. Scegli tra: %types%'),
    ('commands.error.cmd_points.user_offline', 'Impossibile trovare l''utente %user%.'),
    ('commands.error.cmd_prefix_blacklist.empty_word', 'La parola non può essere vuota.'),
    ('commands.error.cmd_prefix_blacklist.usage', 'Utilizzo: :prefixblacklist <add|remove|list> [parola]'),
    ('commands.error.cmd_promote_offer.not_found', 'Impossibile trovare l''offerta. Utilizza :promoteoffer info per visualizzare un elenco di offerte attive.'),
    ('commands.error.cmd_pull.cant_reach', 'L''utente %user% è troppo lontano!'),
    ('commands.error.cmd_pull.invalid', 'Non puoi trascinare %username% lì.'),
    ('commands.error.cmd_pull.not_found', 'Impossibile trovare l''utente %user%!'),
    ('commands.error.cmd_pull.pull_self', 'Non puoi tirarti su!'),
    ('commands.error.cmd_push.cant_reach', 'L''utente %user% è troppo lontano!'),
    ('commands.error.cmd_push.invalid', 'Non puoi spingere %username% lì.'),
    ('commands.error.cmd_push.not_found', 'Impossibile trovare l''utente %user%!'),
    ('commands.error.cmd_push.push_self', 'Non puoi spingerti oltre!'),
    ('commands.error.cmd_remove_prefix.invalid_id', 'ID prefisso non valido. Deve essere un numero o "tutti".'),
    ('commands.error.cmd_remove_prefix.not_found', 'Prefisso non trovato per questo utente.'),
    ('commands.error.cmd_remove_prefix.usage', 'Utilizzo: :removeprefix <username> <id|all>'),
    ('commands.error.cmd_remove_prefix.user_not_found', 'Utente non trovato o non online.'),
    ('commands.error.cmd_roomalert.empty', 'Si prega di specificare un messaggio!'),
    ('commands.error.cmd_roombadge.no_badge', 'Nessun distintivo specificato!'),
    ('commands.error.cmd_roomeffect.no_effect', 'Nessun effetto specificato!'),
    ('commands.error.cmd_roomeffect.numbers_only', 'Usa solo numeri!'),
    ('commands.error.cmd_roomeffect.positive', 'Solo numeri positivi!'),
    ('commands.error.cmd_roomitem.no_item', 'Nessun ID articolo specificato!'),
    ('commands.error.cmd_roomitem.positive', 'Solo numeri positivi!'),
    ('commands.error.cmd_say.forgot_username', 'Si prega di fornire un nome utente!'),
    ('commands.error.cmd_say.hotel_view', '%user% non è in una stanza!'),
    ('commands.error.cmd_say.user_not_found', 'Utente non trovato.'),
    ('commands.error.cmd_say_all.forgot_message', 'Specifica un messaggio!'),
    ('commands.error.cmd_setmax.forgot_number', 'Nessun numero specificato. Stupido.'),
    ('commands.error.cmd_setmax.invalid_number', 'Numero non valido. Specificare un numero compreso tra 0 e 9999'),
    ('commands.error.cmd_setroom_template', 'Impossibile salvare la stanza come modello. Controlla il registro del server per i dettagli.'),
    ('commands.error.cmd_setroom_template.no_room', 'Devi essere all''interno di una stanza per usare questo comando.'),
    ('commands.error.cmd_setspeed.bounds', 'Utilizza un numero compreso tra 0 e 100.'),
    ('commands.error.cmd_setspeed.invalid_amount', 'Si prega di utilizzare un numero valido.'),
    ('commands.error.cmd_set_poll.invalid_number', 'Si prega di specificare un numero valido. Utilizzare 0 per rimuovere il sondaggio.'),
    ('commands.error.cmd_set_poll.missing_arg', 'ID sondaggio mancante. Usa 0 per rimuovere il sondaggio da questa stanza.'),
    ('commands.error.cmd_set_poll.not_found', 'Sondaggio %id% non trovato!'),
    ('commands.error.cmd_shout.forgot_username', 'Si prega di fornire un nome utente!'),
    ('commands.error.cmd_shout.hotel_view', '%user% non è in una stanza!'),
    ('commands.error.cmd_shout.user_not_found', 'Utente non trovato.'),
    ('commands.error.cmd_shout_all.forgot_message', 'Specifica un messaggio!'),
    ('commands.error.cmd_snowwar_save.no_model', 'La riga del modello di stanza SnowWar manca in room_models.'),
    ('commands.error.cmd_snowwar_save.wrong_room', 'Questa stanza non utilizza il modello dell''arena SnowWar.'),
    ('commands.error.cmd_softkick_error_self', 'Non puoi prenderti gioco di te stesso!'),
    ('commands.error.cmd_softkick_not_found', '%user% non trovato'),
    ('commands.error.cmd_staffalert.forgot_message', 'Si prega di specificare un messaggio da inviare allo staff.'),
    ('commands.error.cmd_staffonline.numbers_only', 'Solo numeri per favore!'),
    ('commands.error.cmd_staffonline.positive_only', 'Solo numeri positivi per favore!'),
    ('commands.error.cmd_stalk.forgot_username', 'Specifica il nome utente dell''Habbo che vuoi seguire!'),
    ('commands.error.cmd_stalk.not_found', '%user% sembra essere offline.'),
    ('commands.error.cmd_stalk.not_room', '%user% sembra essere fuori da una stanza.'),
    ('commands.error.cmd_subscription.invalid_action', 'Azione specificata non valida. Deve essere aggiunto, +, rimuovi o -'),
    ('commands.error.cmd_subscription.invalid_params', 'Formato del comando non valido'),
    ('commands.error.cmd_subscription.invalid_params_time', 'Intervallo di tempo non valido, prova: x minuti/giorni/settimane/mesi'),
    ('commands.error.cmd_subscription.success_add_time', 'Aggiunti %time% secondi a %subscription% il %user% riusciti'),
    ('commands.error.cmd_subscription.success_remove_sub', 'Rimozione secondaria %subscription% da %user% riuscita'),
    ('commands.error.cmd_subscription.success_remove_time', 'Rimosso con successo %time% secondi da %subscription% il %user%'),
    ('commands.error.cmd_subscription.type_not_found', '%subscription% non è un tipo di abbonamento valido'),
    ('commands.error.cmd_subscription.user_not_found', '%user% non è stato trovato'),
    ('commands.error.cmd_subscription.user_not_have', '%user% non ha l''abbonamento %subscription%'),
    ('commands.error.cmd_summon.forgot_username', 'Specifica il nome utente dell''Habbo che vuoi evocare!'),
    ('commands.error.cmd_summon.not_found', '%% non è in linea!'),
    ('commands.error.cmd_super_ban.ban_self', 'Non puoi superban te stesso!'),
    ('commands.error.cmd_take_badge.forgot_badge', 'Nessun distintivo specificato!'),
    ('commands.error.cmd_take_badge.forgot_username', 'Nessun nome utente specificato!'),
    ('commands.error.cmd_take_badge.no_badge', '%username% non ha %badge%!'),
    ('commands.error.cmd_unban.not_found', 'Nessun ban trovato per %user%.'),
    ('commands.error.cmd_unban.not_specified', 'Nessun nome utente specificato!'),
    ('commands.error.cmd_unban.success', '%user% è stato sbloccato.'),
    ('commands.error.cmd_unmute.not_found', '%user% non è online!'),
    ('commands.error.cmd_unmute.not_muted', '%user% non è disattivato.'),
    ('commands.error.cmd_unmute.not_specified', 'Nessun utente specificato per riattivare l''audio!'),
    ('commands.error.cmd_update_texts.failed', 'Impossibile aggiornare i testi!'),
    ('commands.error.cmd_userinfo.forgot_username', 'Si prega di fornire un nome utente!'),
    ('commands.error.cmd_userinfo.not_found', 'Utente %user% non trovato!'),
    ('commands.errors.cmd_give_rank.not_found', 'Impossibile assegnare il grado %id% a %username% poiché non esiste!'),
    ('commands.errors.cmd_hidewired.permission', 'Non hai il permesso di nascondere i cavi in ​​questa stanza!'),
    ('commands.generic.cmd_badge.received', 'Yahoooooo! Hai ricevuto un badge!'),
    ('commands.generic.cmd_commands.text', 'I tuoi comandi'),
    ('commands.generic.cmd_coords.title', '<b>Le tue coordinate attuali</b>'),
    ('commands.generic.cmd_credits.received', 'Whoah! Hai ricevuto %amount% crediti!'),
    ('commands.generic.cmd_duckets.received', 'Whoah! Hai ricevuto %amount% duckets!'),
    ('commands.generic.cmd_give_rank.new_rank', 'Il tuo grado è stato aggiornato. Il tuo grado ora è %id%'),
    ('commands.generic.cmd_give_respect_points.received', 'Hai ricevuto %amount% punti rispetto da spendere. Nuovo saldo: %total%.'),
    ('commands.generic.cmd_pet_info.stats', '<b>Statistiche animale domestico:</b>'),
    ('commands.generic.cmd_pet_info.title', '<b>Informazioni sugli animali domestici</b>'),
    ('commands.generic.cmd_points.received', 'Whoah! Hai ricevuto %amount% %type%!'),
    ('commands.generic.cmd_staffalert.title', '<b>Avviso personale:</b>'),
    ('commands.generic.cmd_staffonline.staffs', '<b>Staff online:</b>'),
    ('commands.generic.cmd_stalk.same_room', '%user% sembra essere già in questa stanza!'),
    ('commands.generic.cmd_stalk.self', 'Ho provato qualcosa di stupido'),
    ('commands.generic.cmd_summon.been_summoned', 'Sei stato convocato da %user%!'),
    ('commands.generic.cmd_summon.same_room', '%user% è già in questa stanza!'),
    ('commands.generic.cmd_summon.self', 'Ho provato qualcosa di stupido.'),
    ('commands.generic.cmd_summon.summoning', 'Evocazione di %user%...'),
    ('commands.generic.cmd_summonrank.error', 'Testa di patata!'),
    ('commands.generic.cmd_transform.line', '%name%'),
    ('commands.generic.cmd_transform.title', 'Sono disponibili i seguenti animali domestici:'),
    ('commands.keys.cmd_about', 'info;about;help'),
    ('commands.keys.cmd_add_youtube_playlist', 'add_youtube;add_playlist;add_youtube_playlist'),
    ('commands.keys.cmd_alert', 'alert;warning'),
    ('commands.keys.cmd_allow_trading', 'tradelock;blocktrading;disabletrade'),
    ('commands.keys.cmd_badge', 'badge;givebadge'),
    ('commands.keys.cmd_ban', 'ban'),
    ('commands.keys.cmd_blockalert', 'blockalerts;blockalert;ignorealerts;ignore_alerts'),
    ('commands.keys.cmd_bots', 'bots'),
    ('commands.keys.cmd_bundle', 'bundle;roombundle'),
    ('commands.keys.cmd_calendar', 'calendar'),
    ('commands.keys.cmd_changename', 'changename;flagme;change_name;namechange'),
    ('commands.keys.cmd_chatcolor', 'chat;chatcolor'),
    ('commands.keys.cmd_commands', 'commands;cmds'),
    ('commands.keys.cmd_connect_camera', 'connectcamera;connect_camera;cameraconnect'),
    ('commands.keys.cmd_control', 'control'),
    ('commands.keys.cmd_coords', 'coords;cordinates;coordinates;position'),
    ('commands.keys.cmd_credits', 'credits;coins'),
    ('commands.keys.cmd_dance', 'dance'),
    ('commands.keys.cmd_danceall', 'danceall;room_dance;roomdance'),
    ('commands.keys.cmd_diagonal', 'diagonal;disablediagonal;diagonally'),
    ('commands.keys.cmd_disconnect', 'dc;disconnect;kill'),
    ('commands.keys.cmd_duckets', 'pixels;duckets'),
    ('commands.keys.cmd_ejectall', 'ejectall;ejectfurni'),
    ('commands.keys.cmd_empty', 'empty'),
    ('commands.keys.cmd_empty_bots', 'emptybots;empty_bots;deletebots'),
    ('commands.keys.cmd_empty_pets', 'emptypets;empty_pets;deletepets'),
    ('commands.keys.cmd_enable', 'enable;effect;eff'),
    ('commands.keys.cmd_event', 'event;roomevent'),
    ('commands.keys.cmd_faceless', 'faceless;face'),
    ('commands.keys.cmd_fastwalk', 'fastwalk;supersonic'),
    ('commands.keys.cmd_filterword', 'filter;banword;filterword'),
    ('commands.keys.cmd_freeze', 'freeze'),
    ('commands.keys.cmd_freeze_bots', 'freeze_bot;freezebot;freezebots;freeze_bots'),
    ('commands.keys.cmd_furnidata', 'furnidata'),
    ('commands.keys.cmd_gift', 'gift'),
    ('commands.keys.cmd_give_prefix', 'giveprefix'),
    ('commands.keys.cmd_give_rank', 'giverank;setrank;give_rank;set_rank'),
    ('commands.keys.cmd_give_respect_points', 'give_respect_points;giverespectpoints;respectpoints'),
    ('commands.keys.cmd_ha', 'hotelalert;ha'),
    ('commands.keys.cmd_hal', 'hal;halink'),
    ('commands.keys.cmd_hand_item', 'handitem;item;hand'),
    ('commands.keys.cmd_happyhour', 'happyhour;happy_hour'),
    ('commands.keys.cmd_hidewired', 'hidewired;hidemywired;wiredbegone'),
    ('commands.keys.cmd_invisible', 'invisible;hideme'),
    ('commands.keys.cmd_ip_ban', 'ipban;banip;ip_ban;ban_ip'),
    ('commands.keys.cmd_kickall', 'room_kick;kickall;roomkick;kick_all'),
    ('commands.keys.cmd_lay', 'lay'),
    ('commands.keys.cmd_list_prefixes', 'listprefixes'),
    ('commands.keys.cmd_machine_ban', 'machineban;banmachine;banmac;macban'),
    ('commands.keys.cmd_massbadge', 'massbadge;hotelbadge'),
    ('commands.keys.cmd_masscredits', 'mass_credits;masscredits'),
    ('commands.keys.cmd_massduckets', 'mass_duckets;massduckets;mass_pixels;masspixels'),
    ('commands.keys.cmd_massgift', 'massgift'),
    ('commands.keys.cmd_masspoints', 'mass_points;masspoints'),
    ('commands.keys.cmd_mimic', 'mimic;copy'),
    ('commands.keys.cmd_moonwalk', 'moonwalk;mj;moon_walk'),
    ('commands.keys.cmd_multi', 'multi'),
    ('commands.keys.cmd_mute', 'mute;shutup'),
    ('commands.keys.cmd_mute_bots', 'mutebots;ignorebots;mute_bots;ignore_bots'),
    ('commands.keys.cmd_mute_pets', 'mutepets;ignorepets;mute_pets;ignore_pets'),
    ('commands.keys.cmd_pet_info', 'pet;pet_info;petinfo'),
    ('commands.keys.cmd_pickall', 'pickall;pickupall'),
    ('commands.keys.cmd_plugins', 'plugins'),
    ('commands.keys.cmd_points', 'diamonds;points'),
    ('commands.keys.cmd_prefix_blacklist', 'prefixblacklist'),
    ('commands.keys.cmd_promote_offer', 'promoteoffer;promotetargetoffer;promote_offer'),
    ('commands.keys.cmd_pull', 'pull'),
    ('commands.keys.cmd_push', 'push'),
    ('commands.keys.cmd_randomword', 'rw'),
    ('commands.keys.cmd_redeem', 'redeem;exchange'),
    ('commands.keys.cmd_reload_room', 'reload_room;reload;reloadroom'),
    ('commands.keys.cmd_remove_prefix', 'removeprefix'),
    ('commands.keys.cmd_roomalert', 'roomalert;room_alert;ra'),
    ('commands.keys.cmd_roombadge', 'roombadge'),
    ('commands.keys.cmd_roomcredits', 'roomcredits;room_credits;roomcoins;room_coins'),
    ('commands.keys.cmd_roomeffect', 'roomeffect;room_effect'),
    ('commands.keys.cmd_roomgift', 'roomgift;room_gift'),
    ('commands.keys.cmd_roomitem', 'roomitem;room_item'),
    ('commands.keys.cmd_roommute', 'roommute;room_mute'),
    ('commands.keys.cmd_roompixels', 'roompixels;room_pixels;roomduckets;room_duckets'),
    ('commands.keys.cmd_roompoints', 'roompoints;room_points'),
    ('commands.keys.cmd_say', 'say;makesay'),
    ('commands.keys.cmd_say_all', 'sayall;say_all'),
    ('commands.keys.cmd_setmax', 'setmax;set_max'),
    ('commands.keys.cmd_setroom_template', 'setroom_template;set_room_template'),
    ('commands.keys.cmd_setspeed', 'speed;setspeed'),
    ('commands.keys.cmd_set_poll', 'setpoll;set_poll'),
    ('commands.keys.cmd_shout', 'makeshout'),
    ('commands.keys.cmd_shout_all', 'shoutall;shout_all;roomshout;room_shout'),
    ('commands.keys.cmd_shutdown', 'stop;shutdown'),
    ('commands.keys.cmd_sit', 'sit'),
    ('commands.keys.cmd_sitdown', 'sitall;sitdown'),
    ('commands.keys.cmd_snowwar_save', 'snowwarsave'),
    ('commands.keys.cmd_softkick', 'softkick'),
    ('commands.keys.cmd_staffalert', 'sa;staffalert'),
    ('commands.keys.cmd_staffonline', 'staffonline;staffs'),
    ('commands.keys.cmd_stalk', 'stalk;follow;rape'),
    ('commands.keys.cmd_stand', 'stand'),
    ('commands.keys.cmd_subscription', 'subscription;sub'),
    ('commands.keys.cmd_summon', 'summon'),
    ('commands.keys.cmd_summonrank', 'summonrank;summonall'),
    ('commands.keys.cmd_superpull', 'spull;superpull'),
    ('commands.keys.cmd_super_ban', 'superban;megaban'),
    ('commands.keys.cmd_take_badge', 'takebadge;take_badge;remove_badge;removebadge'),
    ('commands.keys.cmd_teleport', 'tele;teleport'),
    ('commands.keys.cmd_transform', 'transform;becomepet'),
    ('commands.keys.cmd_trash', 'trash;tornado;sharknado'),
    ('commands.keys.cmd_unban', 'unban'),
    ('commands.keys.cmd_unload', 'crash;unload'),
    ('commands.keys.cmd_unmute', 'unmute'),
    ('commands.keys.cmd_update_achievements', 'uach;update_achievements'),
    ('commands.keys.cmd_update_all', 'update_all'),
    ('commands.keys.cmd_update_bots', 'update_bots;updatebots'),
    ('commands.keys.cmd_update_calendar', 'update_calendar'),
    ('commands.keys.cmd_update_catalogue', 'reload_catalogue;reload_cata;update_catalogue;update_cata;update_catalog;update_shop'),
    ('commands.keys.cmd_update_chat_bubbles', 'update_chat_bubbles'),
    ('commands.keys.cmd_update_config', 'update_config;update_configuration'),
    ('commands.keys.cmd_update_guildparts', 'update_guildparts;update_guild_parts'),
    ('commands.keys.cmd_update_hotel_view', 'update_view;update_hotel_view;update_hotelview'),
    ('commands.keys.cmd_update_items', 'update_items;reload_items'),
    ('commands.keys.cmd_update_navigator', 'update_navigator;update_nav'),
    ('commands.keys.cmd_update_permissions', 'update_permissions;update_perms'),
    ('commands.keys.cmd_update_pet_data', 'update_pet_data;update_petdata'),
    ('commands.keys.cmd_update_plugins', 'update_plugins;updateplugins'),
    ('commands.keys.cmd_update_polls', 'update_polls;reload_polls'),
    ('commands.keys.cmd_update_texts', 'update_texts;reload_texts'),
    ('commands.keys.cmd_update_words', 'update_words'),
    ('commands.keys.cmd_update_youtube_playlists', 'update_youtube;update_youtube_playlists'),
    ('commands.keys.cmd_userinfo', 'userinfo;user_info'),
    ('commands.keys.cmd_word_quiz', 'wordquiz;quiz'),
    ('commands.keys.update_wordfilter', 'update_wordfilter;update_filter;update_word_filter'),
    ('commands.succes.cmd_add_youtube_playlist', 'La playlist è stata aggiunta con successo!'),
    ('commands.succes.cmd_alert.cmd_connect_camera', 'Fotocamera ricollegata!'),
    ('commands.succes.cmd_alert.message_send', 'Invia avviso a %user%'),
    ('commands.succes.cmd_allow_trading.disabled', 'Il trading è stato disabilitato per %username%!'),
    ('commands.succes.cmd_allow_trading.enabled', 'Il trading è stato abilitato per %username%!'),
    ('commands.succes.cmd_badge.given', 'Dato %badge% a %user%!'),
    ('commands.succes.cmd_ban.ban_issued', '%user% escluso per %time% secondi con motivo %reason%'),
    ('commands.succes.cmd_blockalert', 'Gli avvisi ora sono diventati %state%'),
    ('commands.succes.cmd_bundle', 'Roombundle creato con successo con ID pagina %id%'),
    ('commands.succes.cmd_chatcolor.reset', 'La chat è stata ripristinata alla normalità'),
    ('commands.succes.cmd_chatcolor.set', 'Il tuo nuovo colore chat è: %chat%'),
    ('commands.succes.cmd_control.controlling', 'Ora stai controllando %user%!'),
    ('commands.succes.cmd_control.stopped', '%user% ora è un uomo libero!'),
    ('commands.succes.cmd_credits.send', '%amount% crediti inviati a %user%!'),
    ('commands.succes.cmd_diagonal.disabled', 'Non puoi più camminare in diagonale!'),
    ('commands.succes.cmd_disconnect.disconnected', '%user% disconnesso!'),
    ('commands.succes.cmd_duckets.send', 'I %amount% i ducketti vengono inviati a %user%!'),
    ('commands.succes.cmd_empty.cleared', 'Inventario svuotato!'),
    ('commands.succes.cmd_empty.verify', 'Ciò rimuoverà tutti gli articoli dal tuo inventario. Digita :empty %generic.yes% per continuare!'),
    ('commands.succes.cmd_empty_bots.cleared', 'L''inventario dei bot è stato svuotato!'),
    ('commands.succes.cmd_empty_bots.verify', 'Ciò rimuoverà tutti i bot dal tuo inventario. Digita :emptybots %generic.yes% per continuare!'),
    ('commands.succes.cmd_empty_pets.cleared', 'Inventario degli animali domestici cancellato!'),
    ('commands.succes.cmd_empty_pets.verify', 'Ciò rimuoverà tutti gli animali domestici dal tuo inventario. Digita :emptypets %generic.yes% per continuare!'),
    ('commands.succes.cmd_filterword.added', 'La parola del filtro parole %word% è stata aggiunta con la sostituzione %replacement%!'),
    ('commands.succes.cmd_freeze.frozen', 'Sei stato congelato!'),
    ('commands.succes.cmd_freeze.unfrozen', 'Sei stato scongelato!'),
    ('commands.succes.cmd_freeze.user_frozen', 'Utente %user% congelato!'),
    ('commands.succes.cmd_freeze.user_unfrozen', 'Utente %user% sbloccato!'),
    ('commands.succes.cmd_freeze_bots.frozen', 'I bot sono ora congelati.'),
    ('commands.succes.cmd_freeze_bots.unfrozen', 'I robot ora possono camminare nella tua stanza.'),
    ('commands.succes.cmd_gift', 'Invia %itemname% a %username%!'),
    ('commands.succes.cmd_give_prefix', 'Prefisso {%prefix%} assegnato con successo a %user%!'),
    ('commands.succes.cmd_give_rank.updated', 'A %username% è stato assegnato il grado %id%'),
    ('commands.succes.cmd_hidewired.hidden', 'Wired è ora nascosto.'),
    ('commands.succes.cmd_hidewired.shown', 'Viene ora visualizzato Wired.'),
    ('commands.succes.cmd_invisible.updated', 'Ora sei invisibile. Ricarica la stanza per resettarla.'),
    ('commands.succes.cmd_invisible.updated.back', 'Ora sei di nuovo visibile.'),
    ('commands.succes.cmd_ip_ban', 'Gli account %count% sono stati bannati dall''IP!'),
    ('commands.succes.cmd_list_prefixes.empty', '%user% non ha prefissi.'),
    ('commands.succes.cmd_list_prefixes.header', 'Prefissi di %user%:'),
    ('commands.succes.cmd_machine_ban', 'Gli account %count% sono stati bannati dal MAC!'),
    ('commands.succes.cmd_mimic.copied', 'Hai copiato %user% %gender_name% guarda!'),
    ('commands.succes.cmd_mute.muted', 'L''utente %user% è ora disattivato.'),
    ('commands.succes.cmd_mute.unmuted', 'L''utente %user% non è più disattivato.'),
    ('commands.succes.cmd_mute_bots.ignored', 'Ora stai ignorando i bot.'),
    ('commands.succes.cmd_mute_bots.unignored', 'Non stai più ignorando i bot.'),
    ('commands.succes.cmd_mute_pets.ignored', 'Ora stai ignorando gli animali domestici.'),
    ('commands.succes.cmd_mute_pets.unignored', 'Non stai più ignorando gli animali domestici.'),
    ('commands.succes.cmd_points.send', '%amount% %type% invia a %user%!'),
    ('commands.succes.cmd_prefix_blacklist.added', 'Parola "%word%" aggiunta alla lista nera dei prefissi.'),
    ('commands.succes.cmd_prefix_blacklist.empty', 'Nessuna parola nella lista nera.'),
    ('commands.succes.cmd_prefix_blacklist.header', 'Parole con prefisso nella lista nera:'),
    ('commands.succes.cmd_prefix_blacklist.removed', 'Parola "%word%" rimossa dalla lista nera dei prefissi.'),
    ('commands.succes.cmd_promote_offer', 'L''offerta promossa è stata modificata in %id%: %title%'),
    ('commands.succes.cmd_pull.pull', '* Tira %user% verso %gender_name% *'),
    ('commands.succes.cmd_push.push', '* Allontana %user% da %gender_name% *'),
    ('commands.succes.cmd_remove_prefix', 'Prefisso #%id% rimosso da %user%.'),
    ('commands.succes.cmd_remove_prefix.all', 'Tutti i prefissi rimossi da %user%.'),
    ('commands.succes.cmd_roomitem.given', 'Oggetto %item% dato!'),
    ('commands.succes.cmd_roomitem.removed', 'Oggetti rimossi!'),
    ('commands.succes.cmd_roommute.muted', 'La stanza è stata disattivata!'),
    ('commands.succes.cmd_roommute.unmuted', 'La stanza è stata riattivata!'),
    ('commands.succes.cmd_say', '%user% ha detto %message%'),
    ('commands.succes.cmd_setroom_template', 'Stanza salvata come ID modello %id% con %items% elementi (%skipped% saltato - item_id non in items_base).'),
    ('commands.succes.cmd_setroom_template.verify', 'Copiare la stanza corrente "%roomname%" in room_templates? Digita :setroom_template %generic.yes% per confermare.'),
    ('commands.succes.cmd_setspeed', 'Successo! Vecchia velocità: %oldspeed%. Nuova velocità: %newspeed%.'),
    ('commands.succes.cmd_set_poll', 'Il sondaggio sulle stanze è stato aggiornato!'),
    ('commands.succes.cmd_shout', '%user% ha gridato %message%'),
    ('commands.succes.cmd_summon.summoned', '%user% evocato!'),
    ('commands.succes.cmd_super_ban', 'Gli account %count% sono stati super bannati!'),
    ('commands.succes.cmd_take_badge', 'Il badge è stato preso!'),
    ('commands.succes.cmd_teleport.disabled', 'Teletrasporto disabilitato!'),
    ('commands.succes.cmd_teleport.enabled', 'Teletrasporto abilitato!'),
    ('commands.succes.cmd_unmute', '%user% è stato riattivato!'),
    ('commands.succes.cmd_update_achievements.updated', 'Gli obiettivi sono stati ricaricati!'),
    ('commands.succes.cmd_update_all', 'Aggiornato tutto con successo!'),
    ('commands.succes.cmd_update_catalog', 'Il catalogo è stato aggiornato!'),
    ('commands.succes.cmd_update_config', 'Configurazione ricaricata!'),
    ('commands.succes.cmd_update_guildparts', 'Successo! Le parti dei badge di gilda e il visualizzatore di badge di gilda sono stati ricaricati!'),
    ('commands.succes.cmd_update_hotel_view', 'Hotelview ricaricato!'),
    ('commands.succes.cmd_update_items', 'Gli articoli sono stati aggiornati!'),
    ('commands.succes.cmd_update_navigator', 'Navigatore ricaricato con successo!'),
    ('commands.succes.cmd_update_permissions', 'Le autorizzazioni sono state aggiornate!'),
    ('commands.succes.cmd_update_pet_data', 'I dati degli animali sono stati aggiornati!'),
    ('commands.succes.cmd_update_plugins', 'Plugin %count% ricaricati!'),
    ('commands.succes.cmd_update_polls', 'I sondaggi sulle stanze sono stati ricaricati!'),
    ('commands.succes.cmd_update_texts', 'Testi aggiornati!'),
    ('commands.succes.cmd_update_wordfilter', 'Filtro parole ricaricato!'),
    ('commands.succes.cmd_update_youtube_playlists', 'Le playlist di YouTube sono state aggiornate!'),
    ('commands.success.cmd_give_respect_points', 'Hai assegnato %amount% punti rispetto a %user%. Nuovo saldo: %total%.'),
    ('commands.success.cmd_setmax', 'Successo! Il numero massimo di utenti in questa stanza virtuale è cambiato in %value%.'),
    ('commands.success.cmd_snowwar_save', 'Arena SnowWar salvata (%count% elementi, %ads% immagini pubblicitarie). Il gioco successivo utilizzerà il nuovo layout.'),
    ('commands.success.cmd_update_calendar', 'Calendario aggiornato con successo!'),
    ('commands.success.cmd_update_chat_bubbles', 'Bolle di chat aggiornate con successo')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

-- Keep literal command arguments intact and polish the most visible automatic translations.
INSERT INTO `emulator_texts` (`key`, `value`) VALUES
    ('commands.description.acc_debug', ':test [header] i:1 s:a b:1'),
    ('commands.description.cmd_chatcolor', ':chat <id colore>'),
    ('commands.description.cmd_enable', ':enable <id>, :effect <id>, :eff <id> oppure :effect list'),
    ('commands.description.cmd_hand_item', ':handitem <id> oppure :handitem list'),
    ('commands.error.cmd_ban.ban_self', 'Non puoi bannare te stesso.')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

-- Lista comandi paginata e alias help italiani.
INSERT INTO `emulator_texts` (`key`, `value`) VALUES
    ('commands.keys.cmd_commands', 'commands;cmds;help;aiuto;comandi'),
    ('commands.description.cmd_commands', ':help [pagina] - Mostra i comandi disponibili per il tuo rank.'),
    ('commands.generic.cmd_commands.text', 'Comandi disponibili'),
    ('commands.generic.cmd_commands.page', 'Pagina %page% di %pages% - %count% comandi'),
    ('commands.generic.cmd_commands.hint', 'Usa :help <pagina> per continuare.'),
    ('commands.error.cmd_commands.invalid_page', 'Pagina non valida. Scegli un numero da 1 a %pages%.'),
    ('commands.generic.cmd_commands.empty', 'Non hai comandi disponibili.')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);
