package com.eu.habbo.habbohotel.catalog;

public enum CatalogPageLayouts {

    default_3x3,
    guild_furni,
    guilds,
    guild_forum,
    info_duckets,
    info_rentables,
    info_loyalty,
    loyalty_vip_buy,
    bots,
    pets,
    pets2,
    pets3,
    club_gift,
    frontpage,
    badge_display,
    spaces_new,
    soundmachine,
    info_pets,
    club_buy,
    roomads,
    trophies,
    single_bundle,
    marketplace,
    marketplace_own_items,
    recycler,
    recycler_info,
    recycler_prizes,
    sold_ltd_items,
    plasto,
    default_3x3_color_grouping,
    recent_purchases,
    room_bundle,
    petcustomization,
    root,
    vip_buy,
    frontpage_featured,
    builders_club_addons,
    builders_club_frontpage,
    builders_club_loyalty,
    monkey,
    niko,
    mad_money
}
